name: build
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: self-hosted
    container:
      image: maven:3.8-amazoncorretto-17
    steps:
      - name: mvn build
        run: |
          mvn -e clean package
